### ISSUE TITLE
M is not defined

### ISSUE THREAD

**Issue by ck37** [berkeley-scf/tutorial-parallel-basics#1]
Hi Chris,

I was going through this tutorial - very useful and helpful. There is one error I got in the RNGstream chunk, where the for loop goes from 1:M but it doesn't seem that M is defined. Maybe it should be nCores there?
## now start M workers

s <- .Random.seed 
for (i in 1:M) { 
    s <- nextRNGStream(s) 
    # send s to worker i as .Random.seed 
} 

Thanks,
Chris

**Comment by paciorek** [comment]
Sort of. That code was not intended to be runnable, as there is no code in
that block that actually starts workers. It was intended as a sketch of how
one would use the functionality...

Thanks keeping a sharp eye out, though!

**Comment by ck37** [comment]
Ah gotcha, that makes sense - closing the issue.
